import { Caveat } from "next/font/google";
import "./globals.css";

const inter = Caveat({ subsets: ["latin"] });

export const metadata = {
  title: "School Registration App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative bg-primary`}>{children}</body>
    </html>
  );
}
